### ISSUE TITLE
Installation issues with OS X

### ISSUE THREAD

**Issue by peekxc** [rcppmlpack/RcppMLPACK1#21]
I'm able to install the CRAN version of RcppMLPACK just fine, however, any attempt at compiling the default package from: 

Let me start by saying that I may be missing something trivial and that perhaps this is an RStudio error, but after installing this library on OS X and getting the initial package skeleton going via: 

`RcppMLPACK::RcppMLPACK.package.skeleton()`

It sets up the package fine. However, when trying to compile the package to use it, `R CMD build .` at the package root directory not seem to work, failing at the command: 

> clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o anRpackage.so RcppExports.o kmeans.o "/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppMLPACK/lib/libRcppMLPACK.a" -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation

with the error:
> clang: error: no such file or directory: '"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppMLPACK/lib/libRcppMLPACK.a"'

However the static lib _is_ there. Fascinatingly, trying to do this by hand, i.e. running the first command from within the source directory seems to work perfectly fine, and then `R CMD install .` from the root directory proceeds as normal. 

I realize this isn't much information to go off of, but would anyone happen to have an idea at least how I can begin to debug this? The output doesn't seem very helpful, and `R CMD build` doesn't seem to have a logging functionality beyond just printing everything

**Comment by eddelbuettel** [comment]
Sorry, just to clarify: this is about the _CRAN package RcppMLPACK_ (which we sometimes refer to as RcppMLPACK1)  as in this repo?   Work on this is somewhat dormant as this package includes a now-stale and outdated version of MLPACK.

Some of us are working (slowly) on a update via [github repo for RcppMLPACK2](https://github.com/rcppmlpack/rcppmlpack2) but I should add that it too has likely build issues on systems other than Linux.  Mixing MLPACK, Armadillo and Boost is not that easy on systems other than Linux as R is quite picky about its compilers.

**Comment by coatless** [comment]
`sessionInfo()` ?

**Comment by peekxc** [comment]
Yes, this is with regard to the CRAN package RppMLPACK, which as understand is this one. 

I did try installing RcppMLPACK2, via devtools: 
`devtools::install_github("rcppmlpack/rcppmlpack2")`

I can get the following objects fine: 
('LARS.o', 'RcppExports.o', 'coverTreeNeighbor.o', 'init.o', 'kMeans.o', 'linearRegression.o', 'logisticRegression.o', 'naiveBayesClassifier.o')

However the next step...: 
`clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o RcppMLPACK.so LARS.o RcppExports.o coverTreeNeighbor.o init.o kMeans.o linearRegression.o logisticRegression.o naiveBayesClassifier.o -L/usr/local/lib -L/usr/local/opt/armadillo/lib/ -L/usr/local/lib/ -L/usr/local/Cellar/mlpack/2.2.0_1/lib/ -lm -l/usr/local/opt/armadillo/lib/libarmadillo.dylib -l/usr/local/lib/libboost_program_options-mt.dylib -l/usr/local/lib/libboost_unit_test_framework-mt.dylib -l/usr/local/lib/libboost_serialization-mt.dylib -lmlpack -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation`

...ends the installation by failing to find armadillo
`ld: library not found for -l/usr/local/opt/armadillo/lib/libarmadillo.dylib`

I have armadillo, and I've used it before, and the dylib exists in that directory. After downloading the package src and trying all of this manually, swapping out  
`-l/usr/local/opt/armadillo/lib/libarmadillo.dylib`
with 
`-L/usr/local/opt/armadillo/lib -larmadillo` 

Gets that part of the job done, but then I run into similar issues for other libs. So, I'm probably forgetting something still trying to figure out that issue for now. 

@coatless 
sessionInfo() output: 
> R version 3.4.0 (2017-04-21)
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> Running under: OS X El Capitan 10.11.6
> 
> Matrix products: default
> BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] anRpackage_1.0
> 
> loaded via a namespace (and not attached):
>  [1] compiler_3.4.0  R6_2.2.1        magrittr_1.5    tools_3.4.0     withr_1.0.2     roxygen2_6.0.1  Rcpp_0.12.11    memoise_1.1.0  
>  [9] xml2_1.1.1      stringi_1.1.5   stringr_1.2.0   digest_0.6.12   commonmark_1.2  devtools_1.13.1

**Comment by eddelbuettel** [comment]
Let's do this one at a time.  

If you want to rebuild RcppMLPACK1 then it should work as CRAN manages to build it.  Could it be that your toolchain is out of whack?   Can you rebuild, say, RcppArmadillo?

We can then talk about RcppMLPACK2 over at its repo.

**Comment by coatless** [comment]
@peekxc Regarding RcppMLPACK2, I'm aware of that error. If you want to see a stream of conscious debugging see:

https://github.com/rcppmlpack/RcppMLPACK1/issues/10#issuecomment-270041922
https://github.com/rcppmlpack/RcppMLPACK1/issues/10#issuecomment-273395022

Regarding the new issue in RcppMLPACK1, I'll need to take a closer look after lunch. Your build is a bit customized.

**Comment by peekxc** [comment]
So, reinstalling the github version of RcppArmadillo worked like a charm, and the whole pipeline works now. 

I can still reproduce the issue if I resort the overwriting the RcppArmadillo package with the CRAN binary. So something is happening there, perhaps local to my machine.

**Comment by peekxc** [comment]
It looks like that issue is perhaps identical to mine, so I think I can close this one.

**Comment by eddelbuettel** [comment]
Interesting.   Could that be a simple "don't mix toolchains" issue?   We have not made changes to RcppArmadillo that I would associate with this -- looks more like a "if in doubt compile all with same compiler" fix.
